apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mrdevops
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
      - name: mrdevops
        image: vinayvkmb/jenk-ansible
        imagepullPolicy: Always
        ports:
        - containerPort: 8080
